### ISSUE TITLE
ios sample is not working

### ISSUE THREAD

**Issue by chykun** [bizzabo/teevid-sdk-samples#4]
Hello
   after clone the project ,when I run and got errors as below : 
ndefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TeeVidClient", referenced from:
      objc-class-ref in ConferenceViewController.o
  "_TEEVID_ATTRIBUTE_VIDEO", referenced from:
      -[ConferenceViewController addViewForParticipant:withAttributes:] in ConferenceViewController.o
  "_TEEVID_ATTRIBUTE_SCREEN_SHARING", referenced from:
      -[ConferenceViewController addViewForParticipant:withAttributes:] in ConferenceViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could anyone help ?

**Comment by Calvinlei** [comment]
@chykun The iOS SDK was updated to work with newest platform (v5.1.x). Please try again.

**Comment by vchavy** [comment]
Closing this issue - please reopen with new information against updated SDK 5.2.X if relevant
